describe('Atrasos em JavaScript', () => {

  it('Validar atraso até aparecer a palavra Liftoff - Usando Wait ', () => {
    cy.visit('https://practice-automation.com/')
    cy.get('div > h1')
      .should('be.visible')
      .should('have.text', 'Welcome to your software automation practice website! ')
    cy.get('a:contains(Delays)').click()
    cy.get('div > h1').should('have.text', 'JavaScript Delays')
    cy.get('#delay').should('not.be.visible')
    cy.get('#start').click()
    cy.get('#delay').should('be.visible')
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '10')
    //Ordenado para aguardar 6 segundos mais os 4 segundos que é default do Cypress
    cy.wait(6000)
    cy.get('#delay')
      .should('have.text', 'Liftoff!')
  })

  it('Validar atraso até aparecer a palavra Liftoff - Usando timeout ', () => {
    cy.visit('https://practice-automation.com/')
    cy.get('div > h1')
      .should('be.visible')
      .should('have.text', 'Welcome to your software automation practice website! ')
    cy.get('a:contains(Delays)').click()
    cy.get('div > h1').should('have.text', 'JavaScript Delays')
    cy.get('#delay').should('not.be.visible')
    cy.get('#start').click()
    cy.get('#delay').should('be.visible')
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '10')
    cy.get('#delay', { timeout: 10000000000000 })
      .should('be.visible')
      .should('have.text', 'Liftoff!')
  })

  it('Validar atraso até aparecer a palavra Liftoff - Validando o cronometro ', () => {
    cy.visit('https://practice-automation.com/')
    cy.get('div > h1')
      .should('be.visible')
      .should('have.text', 'Welcome to your software automation practice website! ')
    cy.get('a:contains(Delays)').click()
    cy.get('div > h1').should('have.text', 'JavaScript Delays')
    cy.get('#delay').should('not.be.visible')
    cy.clock()
    cy.get('#start').click()
    cy.get('#delay').should('be.visible')
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '10')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '9')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '8')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '7')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '6')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '5')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '4')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '3')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '2')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', '1')
    cy.tick(1000)
    cy.get('#delay')
      .should('be.visible')
      .should('have.text', 'Liftoff!')
  })

  it('Validar layout do botão Start ', () => {
    cy.visit('https://practice-automation.com/')
    cy.get('div > h1')
      .should('be.visible')
      .should('have.text', 'Welcome to your software automation practice website! ')
    cy.get('a:contains(Delays)').click()
    cy.get('div > h1').should('have.text', 'JavaScript Delays')
    cy.get('#start')
      .should('have.css', 'background-color', 'rgb(0, 170, 239)')
      .and('have.css', 'color', 'rgb(255, 255, 255)')
      .and('have.css', 'border-radius', '6px')
      .and('have.css', 'text-align', 'center')
      .and('have.css', 'font-family', 'Spartan, sans-serif')
      //.and('have.css', 'height', '46.66250228881836px')
      .and('have.css', 'height').should('include', '46.6')
    cy.get('#start')
      //.and('have.css', 'width', '186.66250610351562px')
      .and('have.css', 'width').should('include', '186.6')
  })
})